export default {
  singleQuote: false,
  trailingComma: "es5",
  tabWidth: 2,
  semi: true,
  jsxSingleQuote: false,
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: "always",
  singleAttributePerLine: true,
  plugins: [
    "prettier-plugin-tailwindcss",
    "@trivago/prettier-plugin-sort-imports",
  ],
  importOrder: [
    "^@/components/(.*)$",
    "^@/composables/(.*)$",
    "^@/constants/(.*)$",
    "^@/db/(.*)$",
    "^@/middleware/(.*)$",
    "^@/routes/(.*)$",
    "^@/services/(.*)$",
    "^@/stores/(.*)$",
    "^@/types/(.*)$",
    "^@/utils/(.*)$",
    "^@/views/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
